IF DB_ID(N'InsuranceManagement_MVC5Db') IS NULL
    CREATE DATABASE [InsuranceManagement_MVC5Db];
GO
USE [InsuranceManagement_MVC5Db];
GO

CREATE TABLE Customer (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    ReferenceNumber NVARCHAR(50) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE InsuranceClaim (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    CustomerId INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE InsurancePlan (
    Id INT IDENTITY PRIMARY KEY,
    PlanCode NVARCHAR(50) NOT NULL,
    PlanName NVARCHAR(150) NOT NULL,
    ProductType NVARCHAR(80) NOT NULL,
    BasePremium DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(30) NOT NULL
);
CREATE TABLE Quote (
    Id INT IDENTITY PRIMARY KEY,
    CustomerId INT NOT NULL,
    PlanId INT NOT NULL,
    Premium DECIMAL(18,2) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE TABLE Policy (
    Id INT IDENTITY PRIMARY KEY,
    CustomerId INT NOT NULL,
    PlanId INT NOT NULL,
    PolicyNumber NVARCHAR(50) NOT NULL,
    StartDate DATE NOT NULL,
    EndDate DATE NOT NULL,
    Status NVARCHAR(30) NOT NULL
);
CREATE TABLE Payment (
    Id INT IDENTITY PRIMARY KEY,
    PolicyId INT NOT NULL,
    Amount DECIMAL(18,2) NOT NULL,
    PaymentDate DATETIME2 NOT NULL,
    Status NVARCHAR(30) NOT NULL
);
CREATE TABLE Endorsement (
    Id INT IDENTITY PRIMARY KEY,
    PolicyId INT NOT NULL,
    RequestType NVARCHAR(100) NOT NULL,
    Status NVARCHAR(30) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
CREATE TABLE AuditLog (
    Id BIGINT IDENTITY PRIMARY KEY,
    EntityName NVARCHAR(100) NOT NULL,
    EntityId INT NOT NULL,
    ActionName NVARCHAR(50) NOT NULL,
    CreatedDate DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
GO
